# Generated by Django 2.2.4 on 2019-09-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.ImageField(default=None, upload_to='post_media'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=20000),
        ),
    ]
