# Generated by Django 2.2.4 on 2019-09-17 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190917_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='media',
            new_name='image',
        ),
    ]
